[package]
name = "ewasm-precompile-keccak256"
version = "0.0.0"
authors = ["Alex Beregszaszi <alex@rtfs.hu>"]
license = "Apache-2.0"
repository = "https://github.com/ewasm/ewasm-precompiles"
description = "Ethereum Keccak-256 precompile in Rust"
publish = false
edition = "2018"

[dependencies]
ewasm_api = "0.5"
keccak-hash = { git = "https://github.com/paritytech/parity-common" }

[lib]
crate-type = ["cdylib"]
